version: "3"

services:
  jenkins:
    image: goffity/docker_jenkins_android
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
    - ./data/jenkins_home:/var/jenkins_home


# master:
#   build: .
#   environment:
#     JAVA_OPTS: "-Djava.awt.headless=true"
#   ports:
#     - "50000:50000"
#     - "8080:8080"
#   volumes:
#     - ./data/jenkins_home:/var/jenkins_home
